services:

  backend:
    build:
      context: ./backend/TaxBankingApi
      dockerfile: dockerfile

    container_name: taxora-backend

    ports:
      - "5106:8080"

    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Data Source=/app/data/taxbanking.db

    volumes:
      - ./backend/TaxBankingApi/taxbanking.db:/app/data/taxbanking.db


  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile

    container_name: taxora-frontend

    ports:
      - "8081:80"

    depends_on:
      - backend